# Generated by Django 6.0.3 on 2026-03-15 23:51

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100, verbose_name='Nombre')),
                ('apellido', models.CharField(max_length=100, verbose_name='Apellido')),
                ('cedula', models.CharField(max_length=20, unique=True, verbose_name='Cedula')),
                ('edad', models.IntegerField(verbose_name='Edad')),
                ('telefono', models.CharField(max_length=15, verbose_name='Teléfono')),
                ('direccion', models.CharField(max_length=200, verbose_name='Dirección')),
                ('email', models.EmailField(max_length=254, verbose_name='Email')),
            ],
        ),
    ]
